
modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId= "create_crystal_clear"
version="0.1e"
displayName="Create: Crystal Clear"
logoFile="logo.png"
authors="Cyvack"
description='''The ultimate Glass Casing Experience.'''

[[dependencies.create_crystal_clear]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_crystal_clear]]
    modId="minecraft"
    mandatory=true
    versionRange="1.18.2"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_crystal_clear]]
modId="create"
mandatory=true
versionRange="0.5.0.e"
ordering="NONE"
side="BOTH"
